simType='sym_file'
symProps = [{'name': 'dryFurRubsSkin', 'RBs': [{'pred_name': 'rubber', 'pred_sem': ['rubber1', 'rubber2', 'rubber3'], 'higher_order': True, 'object_name': 'non_exist', 'object_sem': [], 'P': 'non_exist', 'childRB': 2}, {'pred_name': 'rubbed', 'pred_sem': ['rubbed1', 'rubbed2', 'rubbed3'], 'higher_order': False, 'object_name': 'skin', 'object_sem': ['skin1', 'skin2', 'skin3'], 'P': 'non_exist'}, {'pred_name': 'dry', 'pred_sem': ['dry1', 'dry2', 'dry3'], 'higher_order': False, 'object_name': 'fur', 'object_sem': ['fur1', 'fur2', 'fur3'], 'P': 'non_exist'}], 'set': 'recipient', 'analog': 0}]

#symProps = [{'name': 'troubledCakesMakeLegs', 'RBs': [{'pred_name': 'maker', 'pred_sem': ['maker1', 'maker2', 'maker3'], 'higher_order': True, 'object_name': 'non_exist', 'object_sem': [], 'P': 'non_exist', 'childRB': 2}, {'pred_name': 'made', 'pred_sem': ['made1', 'made2', 'made3'], 'higher_order': False, 'object_name': 'legs', 'object_sem': ['legs1', 'legs2', 'legs3'], 'P': 'non_exist'}, {'pred_name': 'troubled', 'pred_sem': ['troubled1', 'troubled2', 'troubled3'], 'higher_order': False, 'object_name': 'cakes', 'object_sem': ['cakes1', 'cakes2', 'cakes3'], 'P': 'non_exist'}], 'set': 'driver', 'analog': 0}]

#symProps = [{'name': 'non_exist', 'RBs': [{'pred_name': 'happy', 'pred_sem': ['rubbed1', 'rubbed2', 'rubbed3'], 'higher_order': False, 'object_name': 'day', 'object_sem': ['skin1', 'skin2', 'skin3'], 'P': 'non_exist'}], 'set': 'driver', 'analog': 0}]

#symProps = [{'name': 'dryFurRubsSkin', 'RBs': [{'pred_name': 'rubber', 'pred_sem': ['rubber1', 'rubber2', 'rubber3'], 'higher_order': True, 'object_name': 'non_exist', 'object_sem': [], 'P': 'non_exist', 'childRB': 2}, {'pred_name': 'rubbed', 'pred_sem': ['rubbed1', 'rubbed2', 'rubbed3'], 'higher_order': False, 'object_name': 'skin', 'object_sem': ['skin1', 'skin2', 'skin3'], 'P': 'non_exist'}, {'pred_name': 'dry', 'pred_sem': ['dry1', 'dry2', 'dry3'], 'higher_order': False, 'object_name': 'fur', 'object_sem': ['fur1', 'fur2', 'fur3'], 'P': 'non_exist'}], 'set': 'driver', 'analog': 0},{'name': 'dryFurRubsSkin', 'RBs': [{'pred_name': 'rubber', 'pred_sem': ['rubber1', 'rubber2', 'rubber3'], 'higher_order': True, 'object_name': 'non_exist', 'object_sem': [], 'P': 'non_exist', 'childRB': 2}, {'pred_name': 'rubbed', 'pred_sem': ['rubbed1', 'rubbed2', 'rubbed3'], 'higher_order': False, 'object_name': 'skin', 'object_sem': ['skin1', 'skin2', 'skin3'], 'P': 'non_exist'}, {'pred_name': 'dry', 'pred_sem': ['dry1', 'dry2', 'dry3'], 'higher_order': False, 'object_name': 'fur', 'object_sem': ['fur1', 'fur2', 'fur3'], 'P': 'non_exist'}], 'set': 'memory', 'analog': 0},{'name': 'bigDogsBarkLoud', 'RBs': [{'pred_name': 'barker', 'pred_sem': ['barker1', 'barker2', 'barker3'], 'higher_order': True, 'object_name': 'non_exist', 'object_sem': [], 'P': 'non_exist', 'childRB': 2}, {'pred_name': 'barked', 'pred_sem': ['barked1', 'barked2', 'barked3'], 'higher_order': False, 'object_name': 'loud', 'object_sem': ['loud1', 'loud2', 'loud3'], 'P': 'non_exist'}, {'pred_name': 'big', 'pred_sem': ['big1', 'big2', 'big3'], 'higher_order': False, 'object_name': 'fur', 'object_sem': ['dogs1', 'dogs2', 'dogs3'], 'P': 'non_exist'}], 'set': 'memory', 'analog': 0},{'name': 'goldLampsShineBright', 'RBs': [{'pred_name': 'shiner', 'pred_sem': ['shiner1', 'shiner2', 'shiner3'], 'higher_order': True, 'object_name': 'non_exist', 'object_sem': [], 'P': 'non_exist', 'childRB': 2}, {'pred_name': 'shined', 'pred_sem': ['shined1', 'shined2', 'shined3'], 'higher_order': False, 'object_name': 'bright', 'object_sem': ['bright1', 'bright2', 'bright3'], 'P': 'non_exist'}, {'pred_name': 'gold', 'pred_sem': ['gold1', 'gold2', 'gold3'], 'higher_order': False, 'object_name': 'lamps', 'object_sem': ['lamps1', 'lamps2', 'lamps3'], 'P': 'non_exist'}], 'set': 'memory', 'analog': 0},{'name': 'someCatsChaseMice', 'RBs': [{'pred_name': 'chaser', 'pred_sem': ['chaser1', 'chaser2', 'chaser3'], 'higher_order': True, 'object_name': 'non_exist', 'object_sem': [], 'P': 'non_exist', 'childRB': 2}, {'pred_name': 'chased', 'pred_sem': ['chased1', 'chased2', 'chased3'], 'higher_order': False, 'object_name': 'mice', 'object_sem': ['mice1', 'mice2', 'mice3'], 'P': 'non_exist'}, {'pred_name': 'some', 'pred_sem': ['some1', 'some2', 'some3'], 'higher_order': False, 'object_name': 'cats', 'object_sem': ['cats1', 'cats2', 'cats3'], 'P': 'non_exist'}], 'set': 'memory', 'analog': 0}]


